### PR TITLE
update to build 1

### PR DESCRIPTION
**Pull request by dnadeau4**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
@isuruf thanks for your help.  I will use your meta.yaml for other libraries I need to update.   I am a bit confused between the "host" and "run" section.

**Comment by isuruf** [comment]
`build` is build tools like compilers. `host` is what you need to build the library. `run` is what you need at runtime

**Comment by doutriaux1** [comment]
@isuruf is there a document for this anywhere

**Comment by isuruf** [comment]
https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#requirements-section

**Comment by dnadeau4** [comment]
@isuruf I did not realized that you pin `libnetcdf to 4.5`. There is a bug in `libnetcdf <=4.5` where reading variables return "0" if the file is bigger than "2Gb".    I will have to pin libnetcdf >=4.6 and remove your `.ci-support/*.yaml` libnetcdf version.

**Pull request merged**
